[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip RP2040 --protocol swd"
# runner = "elf2uf2-rs -d"
runner = "picotool load -u -v -x -t elf"

# rustflags = [
#   "-C", "linker=flip-link",
#
#   "-C", "link-arg=--nmagic",
#   "-C", "link-arg=-Tlink.x",
#   "-C", "link-arg=-Tlink-rp.x",
#   "-C", "link-arg=-Tdefmt.x",
#
#   "-C", "no-vectorize-loops",
#   "-Z", "trap-unreachable=no",
# ]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"

