name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Prepare
      run: |
        rustup target add thumbv8m.main-none-eabihf
        export PICO_SDK_PATH=$PWD/pico-sdk
        mkdir -p picotool/build
        cd picotool/build
        cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
        make
    - name: Build
      run: make image
